---

- name: Make tempfile for helm installer
  tempfile:
    state: file
  register: helm_installer
  notify: Remove helm installer

- name: Get helm installer script
  get_url:
    url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
    dest: "{{ helm_installer.path }}"

- name: Install specified version of helm
  command: >
    /bin/bash {{ helm_installer.path }}/get-helm-3 --version {{ helm_version }}
  environment:
    PATH: '/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin'