---

- name: Download Helm Binary
  get_url:
    url: https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin/helm
    owner: root
    group: root
    mode: 0555
  become: true
  
